#<!-- METADATA START --> # DO NOT DELETE THIS LINE
# All example text is surrounded with <ex> and </ex>. Please replace the example
# text including the <ex> and </ex> with your data. Delete all non-applicable
# lines and sections.

# Attention: indentation is important and must be preserved!

# information on the study the to-be-archived dataset was created for

# mandatory information on to-be-archived dataset
dataset:
  # short name or label
  name: DataLad Catalog Demo

  # current location of the dataset
  location: https://github.com/jsheunis/datalad-catalog-demo-super

  # summary of purpose and content of the dataset
  description:
    "This catalog is a demonstration of the decentralized data portal functionality of
    the open source data management tool, DataLad (www.datalad.org). The catalog enables
    discoverability of multiple heterogeneous collections of data without relying on a
    centrally maintained database, hosting service, or (meta)data standard. The catalog
    is generated entirely from harmonized metadata, while the respective datasets are
    hosted and maintained independently of each other. This is achieved by DataLad's
    capability to represent collections of data as modular, structured, and machine
    actionable units (DataLad datasets), followed by adding and extracting metadata
    (with datalad-metalad: https://github.com/datalad/datalad-metalad), and finally
    harmonizing and rendering metadata in the catalog that you are vieweing (using
    datalad-catalog: https://github.com/datalad/datalad-metalad).

    The provenance tracking functionality of DataLad allows all steps leading to the
    final state of the catalog to encapsulated in a DataLad dataset. This includes the
    linking of sub-datasets (i.e. all the datasets in the catalog), extraction of metadata,
    metadata harmionization, and lastly the generation of the catalog and all its entries.
    Such provenance records are easily re-executable, meaning that with the required
    software tools installed, anyone should be able to reproduce the same outcome.

    Browse the catalog and its datasets to explore its functionality.
    "

  # optional list of employed standard and format
  # for automatic generation of rich metadata records
  # (see handbook for full list)

  # optional list of keyword/phrase
  keyword:
    - research data
    - data management
    - metadata
    - catalog
    - DataLad
    - machine actionable
    - FAIR
    - harmonization

  # minimum of one dataset author required
  author:
    - a@fz-juelich.de

# person information, one record for every email-key used above
person:
  a@fz-juelich.de:
     given_name: Stephan
     last_name: Heunis

#<!-- METADATA END -->  # DO NOT DELETE THIS LINE